const nirfEngineering = [
  { rank:1, name:"Indian Institute of Technology Madras", type:'Engineering-Rankings', state:"Tamil Nadu", city:"Chennai", website:"https://www.iitm.ac.in" },
  { rank:2, name:"Indian Institute of Technology Delhi", type:'Engineering-Rankings', state:"Delhi", city:"New Delhi", website:"https://home.iitd.ac.in" },
  { rank:3, name:"Indian Institute of Technology Bombay", type:'Engineering-Rankings', state:"Maharashtra", city:"Mumbai", website:"https://www.iitb.ac.in" },
  { rank:4, name:"Indian Institute of Technology Kanpur", type:'Engineering-Rankings', state:"Uttar Pradesh", city:"Kanpur", website:"https://www.iitk.ac.in" },
  { rank:5, name:"Indian Institute of Technology Kharagpur", type:'Engineering-Rankings', state:"West Bengal", city:"Kharagpur", website:"https://www.iitkgp.ac.in" },
  { rank:6, name:"Indian Institute of Technology Roorkee", type:'Engineering-Rankings', state:"Uttarakhand", city:"Roorkee", website:"https://www.iitr.ac.in" },
  { rank:7, name:"Indian Institute of Technology Hyderabad", type:'Engineering-Rankings', state:"Telangana", city:"Hyderabad", website:"https://iith.ac.in" },
  { rank:8, name:"Indian Institute of Technology Guwahati", type:'Engineering-Rankings', state:"Assam", city:"Guwahati", website:"https://www.iitg.ac.in" },
  { rank:9, name:"National Institute of Technology Tiruchirappalli", type:'Engineering-Rankings', state:"Tamil Nadu", city:"Tiruchirappalli", website:"https://www.nitt.edu" },
  { rank:10, name:"Indian Institute of Technology (Banaras Hindu University) Varanasi", type:'Engineering-Rankings', state:"Uttar Pradesh", city:"Varanasi", website:"https://www.iitbhu.ac.in" },
  { rank:11, name:"Birla Institute of Technology & Science -Pilani", type:'Engineering-Rankings', state:"Rajasthan", city:"Pilani", website:"https://www.bits-pilani.ac.in" },
  { rank:12, name:"Indian Institute of Technology Indore", type:'Engineering-Rankings', state:"Madhya Pradesh", city:"Indore", website:"https://www.iiti.ac.in" },
  { rank:13, name:"National Institute of Technology Rourkela", type:'Engineering-Rankings', state:"Odisha", city:"Rourkela", website:"https://www.nitrkl.ac.in" },
  { rank:14, name:"S.R.M. Institute of Science and Technology", type:'Engineering-Rankings', state:"Tamil Nadu", city:"Chennai", website:"https://www.srmist.edu.in" },
  { rank:15, name:"Indian Institute of Technology (Indian School of Mines)", type:'Engineering-Rankings', state:"Jharkhand", city:"Dhanbad", website:"https://www.iitism.ac.in" },
  { rank:16, name:"Vellore Institute of Technology", type:'Engineering-Rankings', state:"Tamil Nadu", city:"Vellore", website:"https://vit.ac.in" },
  { rank:17, name:"National Institute of Technology Karnataka, Surathkal", type:'Engineering-Rankings', state:"Karnataka", city:"Surathkal", website:"https://www.nitk.ac.in" },
  { rank:18, name:"Jadavpur University", type:'Engineering-Rankings', state:"West Bengal", city:"Kolkata", website:"https://www.jaduniv.edu.in" },
  { rank:19, name:"Indian Institute of Technology Patna", type:'Engineering-Rankings', state:"Bihar", city:"Patna", website:"https://www.iitp.ac.in" },
  { rank:20, name:"Anna University", type:'Engineering-Rankings', state:"Tamil Nadu", city:"Chennai", website:"https://www.annauniv.edu" },
  { rank:21, name:"National Institute of Technology Calicut", type:'Engineering-Rankings', state:"Kerala", city:"Kozhikode", website:"https://nitc.ac.in" },
  { rank:22, name:"Siksha `O` Anusandhan", type:'Engineering-Rankings', state:"Odisha", city:"Bhubaneswar", website:"https://www.soa.ac.in" },
  { rank:23, name:"Amrita Vishwa Vidyapeetham", type:'Engineering-Rankings', state:"Tamil Nadu", city:"Coimbatore", website:"https://www.amrita.edu" },
  { rank:24, name:"Jamia Millia Islamia", type:'Engineering-Rankings', state:"Delhi", city:"New Delhi", website:"https://www.jmi.ac.in" },
  { rank:25, name:"Indian Institute of Technology Gandhinagar", type:'Engineering-Rankings', state:"Gujarat", city:"Gandhinagar", website:"https://www.iitgn.ac.in" },
  { rank:26, name:"Indian Institute of Technology Mandi", type:'Engineering-Rankings', state:"Himachal Pradesh", city:"Mandi", website:"https://www.iitmandi.ac.in" },
  { rank:27, name:"Indian Institute of Technology Jodhpur", type:'Engineering-Rankings', state:"Rajasthan", city:"Jodhpur", website:"https://iitj.ac.in" },
  { rank:28, name:"National Institute of Technology Warangal", type:'Engineering-Rankings', state:"Telangana", city:"Warangal", website:"https://www.nitw.ac.in" },
  { rank:29, name:"Thapar Institute of Engineering and Technology (Deemed-to-be-university)", type:'Engineering-Rankings', state:"Punjab", city:"Patiala", website:"https://www.thapar.edu" },
  { rank:30, name:"Delhi Technological University", type:'Engineering-Rankings', state:"Delhi", city:"New Delhi", website:"https://www.dtu.ac.in" },
  // TODO: Add ranks 31–100 here for full coverage.
];